export const kinds = [
  { text: '전체', value: '' },
  { text: '밑반찬', value: 'SIDE' },
  { text: '메인반찬', value: 'MAIN' },
  { text: '국/탕', value: 'GUG_TANG' },
  { text: '찌개', value: 'STEW' },
  { text: '디저트', value: 'DESSERT' },
  { text: '면/만두', value: 'NOODLE' },
  { text: '밥/죽/떡', value: 'RICE' },
  { text: '퓨전', value: 'FUSION' },
  { text: '김치/젓갈/장류', value: 'PASTE' },
  { text: '양념/소스/잼', value: 'SAUCE' },
  { text: '양식', value: 'WESTERN' },
  { text: '샐러드', value: 'SALAD' },
  { text: '스프', value: 'SOUP' },
  { text: '빵', value: 'BREAD' },
  { text: '과자', value: 'SNACK' },
  { text: '차/음료/술', value: 'DRINK' },
  { text: '기타', value: 'OTHERS' },
];

export const situations = [
  { text: '전체', value: '' },
  { text: '일상', value: 'ROUTINE' },
  { text: '초스피드', value: 'SPEED' },
  { text: '손님접대', value: 'SERVE' },
  { text: '술안주', value: 'SIDE' },
  { text: '다이어트', value: 'DIET' },
  { text: '도시락', value: 'BOXED' },
  { text: '영양식', value: 'NUTRITIONAL' },
  { text: '간식', value: 'SNACK' },
  { text: '야식', value: 'NIGHT' },
  { text: '푸드스타일링', value: 'STYLING' },
  { text: '해장', value: 'HANGOVER' },
  { text: '명절', value: 'HOLIDAY' },
  { text: '이유식', value: 'BABY' },
  { text: '기타', value: 'OTHERS' },
];

export const ingredients = [
  { text: '전체', value: '' },
  { text: '소고기', value: 'BEEF' },
  { text: '돼지고기', value: 'PORK' },
  { text: '닭고기', value: 'CHICKEN' },
  { text: '육류', value: 'MEAT' },
  { text: '채소류', value: 'VEGETABLES' },
  { text: '해물류', value: 'SEAFOOD' },
  { text: '달걀유제품', value: 'EGG_DAILY' },
  { text: '가공식품류', value: 'PROCESSED' },
  { text: '쌀', value: 'RICE' },
  { text: '밀가루', value: 'FLOUR' },
  { text: '건어물류', value: 'DRIED' },
  { text: '버섯류', value: 'MUSHROOMS' },
  { text: '과일류', value: 'FRUITS' },
  { text: '콩/견과류', value: 'BEANS_NUTS' },
  { text: '곡류', value: 'CEREALS' },
  { text: '기타', value: 'OTHERS' },
];

export const methods = [
  { text: '전체', value: '' },
  { text: '볶음', value: 'STIR_FRIED' },
  { text: '끓이기', value: 'BOIL' },
  { text: '부침', value: 'SERVE' },
  { text: '조림', value: 'BOILED' },
  { text: '무침', value: 'SALTED' },
  { text: '비빔', value: 'MIX' },
  { text: '찜', value: 'STEAMED' },
  { text: '절임', value: 'PICKLED' },
  { text: '튀김', value: 'FRIED' },
  { text: '삶기', value: 'SIMMER' },
  { text: '굽기', value: 'BAKE' },
  { text: '데치기', value: 'BLANCH' },
  { text: '회', value: 'SASHIMI' },
  { text: '기타', value: 'OTHERS' },
];
